version: '3'
services:
  nibbles:
    build: 
      context: ./frontend
    volumes:
      - ./frontend/dist:/app/dist
      - ./frontend/bin:/app/bin
    ports:
      - "9090:9000"
    entrypoint: npm run dev
  nibblejs:
    build: 
      context: ./nibbleappjs
    volumes:
      - ./nibbleappjs/server.js:/app/server.js
    ports:
      - "9091:9000"
    entrypoint: npm run dev
  nibblets:
    build:
      context: ./nibbleAppTS
    volumes:
      - ./nibbleAppTS/dist:/app/dist
      - ./nibbleAppTS/bin:/app/bin
    ports:
      - "9092:9000"
    entrypoint: npm run dev
